apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-task-app
  template:
    metadata:
      labels:
        app: brain-task-app
    spec:
      containers:
      - name: brain-task-app
        image: 336832361054.dkr.ecr.us-east-2.amazonaws.com/deployment/brain-task-app:v1 
        ports:
        - containerPort: 3000